{
 "title": "RomanNumeral",
 "description": "Request Latency ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Req Frequency",
   "type": "timeseries",
   "description": "Req frequency for /romannumeral",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri=~\"/romannumeral\"}[1m])"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "/romannumeral request latency",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=~\"/romannumeral\"}[1m])/rate(http_server_requests_seconds_count{uri=~\"/romannumeral\"}[1m])"
    }
   ]
  },
  {
   "title": "Exception Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{exception=~\"MethodArgumentTypeMismatchException|OutOfRangeException\"}[1m])) by (exception)"
    }
   ]
  }
 ]
}